### PR TITLE
Configure animation, access DropdownController.showing, change TableController.items

### PR DESCRIPTION
**Pull request by yonat**
@onmyway133 Thanks for this useful pod!

I made some changes needed for a client's app, hope others will find them useful too.

### CODE REVIEW

**Comment by onmyway133** [comment]
@yonat Hi, glad that you found this helpful 👍

**Comment by yonat** [comment]
Thanks for merging!
Please tag `3.1.0` and then `pod trunk push` .

**Comment by yonat** [comment]
@onmyway133 Hi, would you tag `3.1.0` and then `pod trunk push` ?
Thanks!

**Comment by onmyway133** [comment]
@yonat here you are https://github.com/onmyway133/Dropdowns/releases/tag/3.1.0

**Comment by yonat** [comment]
Thanks!

**Pull request merged**
